HTTP: ## the keys must be strings that exist inside of the inital header message
  "test.test" : 
    port: 6970
    priority: latency
  "jobs.test" : 
    port: 6970
    priority: throughput
  "shop.test" : 
    port: 3001
    priority: throughput
  "default" : 
    port: 80
    priority: latency
HTTPS:
  "test.test" : 
    port: 3000
    priority: latency
  "shop.test" : 
    port: 3001
    priority: latency
  "jobs.test" :
    port: 3002
    priority: throughput
  "default" : 
    port: 443
    priority: both
OPENVPN:
  "default" : 1194
  priority : both 
SSH:
  "default" : 22
SFTP:
  "default" : 22
  priority : throughput
