http: ## the keys must be strings that exist inside of the inital header message
  "test.test" : 6969
  "jobs.test" : 6970
  "default" : 80
https:
  "test.test" : 3000
  "shop.test" : 3001
  "jobs.test" : 3002
  "default" : 80
openvpn:
  "default" : 1194
ssh:
  "default" : 22
sftp:
  "default" : 80
user:

