HTTP: ## the keys must be strings that exist inside of the inital header message
  "test.test" : 
    port: 6970
    priority: latency
  "jobs.test" : 
    port: 6970
    priority: throughput
  "shop.test" : 
    port: 3001
    priority: throughput
  "default" : 
    port: 80
    priority: latency
HTTPS:
  "test.test" : 
    port: 3000
    priority: latency
  "shop.test" : 
    port: 3001
    priority: latency
  "jobs.test" :
    port: 3002
    priority: throughput
  "default" : 
    port: 443
    priority: both
OPENVPN:
  "default" : 1194
  priority : both 
SSH:
  "default" : 22
SFTP:
  "default" : 80
  priority : throughput
USER:
  "[abc][123][def][456]" : 
    port: 6969
    priority: both 
  "[abc][456][def]" : 
    port: 8900
    priority: both
  "default" :
    port: 48778
    priority: both