http: ## the keys must be strings that exist inside of the inital header message
  "www.youtube.com" : 6969
  "127.0.0.1:8080" : 6970
https:
  "test.test" : 3000
  "shop.test" : 3001
  "jobs.test" : 3002
openvpn:
  "1": 1194
ssh:
  "1" : 22
sftp:
  "1" : 22
user:

